### ISSUE TITLE
Napari plugin

### ISSUE THREAD

**Issue by vilim** [portugueslab/split_dataset#3]
with the new [napari plugin](https://napari.org/docs/plugins/for_plugin_developers.html) architecture, so that datasets can just be dropped into napari. See also [the template](https://github.com/napari/cookiecutter-napari-plugin)

**Comment by vigji** [comment]
Here or fimpy or both?

**Comment by vilim** [comment]
it should be fimpy independent, no? I think it would be good if this package could provide a napari plugin, just by adding a small dependency: https://github.com/napari/napari-plugins

**Comment by vigji** [comment]
it should be a separate package though

**Comment by vilim** [comment]
it can be, but I don't think it needs to be. if you look at this https://github.com/tlambert03/napari-dv/blob/master/napari_dv.py it is just one small file with this one extra dependency. After implementing the dask array creation, it is literally a 3-liner, for which an extra package seems superfluous.

**Comment by vigji** [comment]
I think it has if you want it to to be in some sort of register

**Comment by vigji** [comment]
Done here:
https://github.com/portugueslab/napari-split-dataset
